# filepath, 3 letter language code, language name
langs = [
 ("ar_pud-ud-test.conllu", "ams", "Arabic"),
 ("hi_pud-ud-test.conllu", "hin", "Hindi"),
 ("pt_pud-ud-test.conllu", "por", "Portuguese"),
 ("cs_pud-ud-test.conllu", "cze", "Czech"),
 ("id_pud-ud-test.conllu", "ind", "Indonesian"),
 ("ru_pud-ud-test.conllu", "rus", "Russian"),
 ("de_pud-ud-test.conllu", "ger", "German"),
 ("is_pud-ud-test.conllu", "ice", "Icelandic"),
 ("sv_pud-ud-test.conllu", "swe", "Swedish"),
 ("en_pud-ud-test.conllu", "eng", "English"),
 ("it_pud-ud-test.conllu", "ita", "Italian"),
 ("th_pud-ud-test.conllu", "tha", "Thai"),
 ("es_pud-ud-test.conllu", "spa", "Spanish"),
 ("tr_pud-ud-test.conllu", "tur", "Turkish"),
 ("fi_pud-ud-test.conllu", "fin", "Finnish"),
 ("ja_pud-ud-test.conllu", "jpn", "Japanese"),
 ("ja_pudluw-ud-test.conllu", "jpn_uw", "Japanese (UW)"),
 ("zh_pud-ud-test.conllu", "mnd", "Mandarin"),
 ("fr_pud-ud-test.conllu", "fre", "French"),
 ("ko_pud-ud-test.conllu", "kor", "Korean"),
 ("pl_pud-ud-test.conllu", "pol", "Polish"),
]
